### ISSUE TITLE
Possible Issue with Voice Selection

### ISSUE THREAD

**Issue by TodWulff** [jneilliii/OctoPrint-M117SpeechSynthesis#11]
Context: OP 1.5.2/0.17/Win10x64/Chrome
Issue:  Selection of Microsoft David as the selected voice isn't sticking across run instances.  Seems as if there might be an issue with the list of voices being zero-based.?.  It presents settings selecting other voices are sticking.

**Comment by jneilliii** [comment]
I think this issue is related to the david voice being an index of 0, and that is causing the knockout binding to be wonky on initial page load. I think instead of storing the values in a 0 based index I may have to increment them by one and save them that way. I will do some additional testing in the near future and see if that will resolve this.

**Comment by jneilliii** [comment]
I think I've been able to resolve this simply by removing the "select voice" option from the pull down list. You can try it out for me by copying/pasting the URL below into plugin manager > get more > ...from URL.

```
https://github.com/jneilliii/OctoPrint-M117SpeechSynthesis/archive/0.5.2rc3.zip
```

**Comment by TodWulff** [comment]
Will test when the current print is complete.  Thanks Jim.

**Comment by jneilliii** [comment]
cool, got to keep 1/139 users happy....lol.

https://jneilliii.github.io/OctoPluginStats/#m117speechsynthesisContainer

edit: oops, looks like my async page building doesn't work with anchors...another thing to fix.

**Comment by TodWulff** [comment]
Issue resolved.  Thanks, Jim.  Merry Christmas, Kind Sir!

**Comment by TodWulff** [comment]
> https://jneilliii.github.io/OctoPluginStats/#m117speechsynthesisContainer
> edit: oops, looks like my async page building doesn't work with anchors...another thing to fix.

I think it just takes a bit of time to receive the page, and with this being down at the bottom, looks to take a bit to get to the point of where it can render those portions of the page being served.
