### ISSUE TITLE
Voice Not Saving After Update

### ISSUE THREAD

**Issue by rebeltaz** [jneilliii/OctoPrint-M117SpeechSynthesis#13]
Oddly enough, I wasn't having any trouble with voices until I let it update the plugin. Now, no matter what voice I select, it reverts back to the first voice in the list (Catalan in my case) every time Firefox is restarted.

**Comment by jneilliii** [comment]
Dang, the last update was to fix an issue where you couldn't pick the first voice as an option. I guess that broke using any other voice although that didn't happen in my initial testing. Potentially a firefox bug. I'll look into it. In the meantime, you could revert the version by using the URL below in Plugin Manager> Get More > ...from URL and clicking Install and then don't upgrade when prompted.

```
https://github.com/jneilliii/OctoPrint-M117SpeechSynthesis/archive/0.5.1.zip
```

**Comment by rebeltaz** [comment]
lol... yep. and that's why I always try not to upgrade softwares if I don't have to. :) I will downgrade. Thanks.

**Comment by jneilliii** [comment]
This is fixed in the newest version I think.
