### ISSUE TITLE
Works in terminal, not in print.

### ISSUE THREAD

**Issue by amarissimus** [jneilliii/OctoPrint-M117SpeechSynthesis#17]
The plugin works just fine when M117 is entered into the terminal in octoprint.  When set as a start/end script, it does not.  I'm using Klipper; I understand that it uses M117 to display text.  What I don't understand is why it would work through the terminal but not as a script.  I see the text on my display when using the terminal and the speech is generated.  As an end script, I only see the text.

**Comment by jneilliii** [comment]
I'm assuming you mean the start/end gcode scripts in OctoPrint's settings? It might be possible that those are being run outside of the gcode queue from OctoPrint and therefore not possible for me to intercept as the commands are getting sent. I would recommend adding the commands to your slicer's start/end gcode settings so they are going through the same queue as the commands that are working. 

I'm not familiar with how klipper works but it's also possible that the print is being sent like from SD card, which also would not process through the sending queue.

**Comment by amarissimus** [comment]
Ah, yes I had not considered the difference between a start/end script in Octoprint vs inside a loaded gcode.  When looking at the command terminal in Octoprint I always imagined the only difference between a gcode file running and manually entering code was the speed of a processor/machine vs my clumsy fingers and brain.  At least with Klipper, this is clearly not the case.  I will see if the result is the same with those commands inside the file generated by the slicer.  And then dive into the klipper developer documentation, most of which is beyond me, but must contain the order of operations for the code flow and the answer to when and why a particular command is diverted or ignored.  I was being naive and myopic in the way I approached it at first.  Thanks for the response.
