### ISSUE TITLE
Feature Request: add option to ignore list of chars in m117

### ISSUE THREAD

**Issue by StefanIGit** [jneilliii/OctoPrint-M117SpeechSynthesis#6]
I have a plugin which sends the print progress like m117 ######### 70%
so this give a funny effect, hear: 
[SoundRecord-2018-01-27-15-55-47.zip](https://github.com/jneilliii/OctoPrint-M117SpeechSynthesis/files/1670179/SoundRecord-2018-01-27-15-55-47.zip)

I'm not really good with regex so maybe you can add it directly in the alert or make  config option.

nice plugin btw :)

**Comment by jneilliii** [comment]
That's going to be tricky.  I think you're using the DetailedProgress or DisplayProgress plugin, which sends M117 commands through to the lcd panel for completion progress, etc.  I'll see if there is a way to ignore those, but I'm not guaranteeing anything. Can you confirm which plugin you are using?

**Comment by StefanIGit** [comment]
Hi I think it is [https://github.com/OctoPrint/OctoPrint-DisplayProgress](this one) since I have it installed and the image looks similar.
bye

**Comment by jneilliii** [comment]
I just released a new version 0.5.0 that allows for enabling a custom gcode command.  This would allow you to bypass the speaking of other M117 commands from the other plugins.  To use, replace any M117 commands in your gcode you want to be spoken to be `@SPEAK`.  So for example if you want to say "Print complete" you would use `@SPEAK Print complete`. Hopefully that works for you.
